spring.application.name=productos-service
server.port=8081

# Eureka (Conexión al contenedor)
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.instance.prefer-ip-address=true

# MongoDB (Con credenciales de Docker Compose)
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://admin:admin@mongodb:27017/productos?authSource=admin}

# Kafka retry topics
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.group-id=productos-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.listener.retry-interval-ms=1000
spring.kafka.listener.retry-max-attempts=3
broker.topics.products=${BROKER_TOPICS_PRODUCTS:product_retry_jobs}
kafka.topics.inventory-updates=${KAFKA_TOPIC_INVENTORY_UPDATES:inventory_update_events}
kafka.topics.payment-received=${KAFKA_TOPIC_PAYMENT_RECEIVED:payment_received_events}
kafka.topics.partitions=${KAFKA_TOPIC_PARTITIONS:1}
kafka.topics.replicas=${KAFKA_TOPIC_REPLICAS:1}

# Logs de Debug para ver la conexión
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
