spring.application.name=productos-service
server.port=8081

# Eureka (Conexión al contenedor)
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.instance.prefer-ip-address=true

# MongoDB (Con credenciales de Docker Compose)
spring.mongodb.uri=mongodb://admin:admin@mongodb:27017/productos?authSource=admin

# Logs de Debug para ver la conexión
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
